### PR TITLE
Add threading support

### PR DESCRIPTION
**Pull request by charliewolf**
This is an implementation of what @lewellyn suggested in #47 to allow users to use threading via IRC.

### CODE REVIEW

**Comment by danpopp** [comment]
:+1:

**Comment by thmzlt** [comment]
I spent the day using the IRC gateway with this code instead of the web app and it worked well. Two things I noticed:

- I can't see the ID of a thread initiated by me until I get a reply. It would be nice if the gateway returned the ID right after I sent the first message.

- The `<123456>` prefix is a bit cumbersome to type. To alleviate that, I would use a single delimiter (e.g. `.`) and convert the ID to a larger base. For example, instead of `<303132> hello!`, one could send `.6hwc hello!` (with radix 36).

**Comment by charliewolf** [comment]
@thmzlt You should be able to see the ID without waiting for a reply. Try a different IRC client? Works on ChatZilla.

Any idea on the best way to implement the radix?

**Comment by thmzlt** [comment]
> You should be able to see the ID without waiting for a reply.

Good point. I was using [irssi](http://www.irssi.org/).

> Any idea on the best way to implement the radix?

You can convert an integer to/from a differnt base using `#to_i` and `#to_s`:

2015-08-14-223739_276x66_scrot

**Comment by jden** [comment]
This feature would be superduper amazing :) :cat2: :cactus: :cake:

**Comment by tzz** [comment]
Suggestion: in addition to `<ID>` accept `~ MESSAGE` for "last thread", `~tzz MESSAGE` for "last thread with user `tzz`", `~~ MESSAGE` for "last thread in which I participated", and `!2 MESSAGE` for "the second previous thread."

This is literally the only thing forcing me and others to use the GUI Flowdock client.

**Comment by jden** [comment]
Is there any interest from flowdock in merging this? Any outstanding concerns? I see that this repo continues to receive new commits. This feature would be very useful to me and I'd like to help if I can.

**Comment by jden** [comment]
~bump~

**Comment by milanaleksic** [comment]
Can we please merge this? Although I am not the author of this PR, I am for quite some time already using it on my machine without issues, so I don't know why we don't have it upstream. Without this oulu is not that usable

**Comment by jden** [comment]
To update my earlier comments on this thread, my team no longer needs this PR since we are switching to Slack, which has excellent IRC support.

**Comment by coldpour** [comment]
I'm sorry guys, but the flowdock team is no longer supporting oulu. You are welcome to fork and run your own server. We'd even be willing to point people to your fork if you'd like. IRC has just been deprioritized. I'm sorry for not following up sooner.

**Comment by trezy** [comment]
@coldpour Would the Flowdock team be willing, then, to transfer ownership of this repository to it's own organization so that the community could then continue managing it?

**Pull request closed without merging**
